### PR TITLE
Generate a site with Jekyll and testing with Travis

### PR DESCRIPTION
**Pull request by bvhme**
This PR adds a website generated with Jekyll/GitHub pages and the Foundation For Public Code jekyll theme.

This PR also adds support for Travis as a tester for testing the integrity of Pull Requests. In this PR it uses `html-proofer` to check for broken links. I'll enable Travis and it **should fail** since there are some missing links.

### CODE REVIEW

**Comment by bvhme** [comment]
Good, it is working.

The `html-proofer` fails on the following:

```
- ./_site/schema.html
  *  internally linking to tags.md, which does not exist (line 328)
     <a href="tags.md">Available tags</a>
  *  linking to internal hash # that does not exist (line 532)
     <a href="#">links</a>
- ./_site/schema.it.html
  *  internally linking to sw-category.md, which does not exist (line 221)
     <a href="sw-category.md">sw-category.md</a>
  *  internally linking to sw-category.md, which does not exist (line 231)
     <a href="sw-category.md">sw-category.md</a>
htmlproofer 3.8.0 | Error:  HTML-Proofer found 4 failures!
```

How shall we handle this, fix this or is it too early for link-checking?

**Comment by ruphy** [comment]
Hi,
I am creating tags.md right now. The link to # should be working, we can remove it in case it creates problems (it's just used as to make the text look like a link). Schema.it is fixed.

**Comment by ruphy** [comment]
Hi Boris,

I think I might have messed something up by trying to update this branch. Could you check if you have local commits that re-enable travis?

**Comment by bvhme** [comment]
Oh wow, crazy, I can't figure out what happened! I'll go take a look at it right away.

**Comment by bvhme** [comment]
Okay, it works again. It does still return the following error:

```
- ./_site/schema.html
  *  linking to internal hash # that does not exist (line 534)
     <a href="#">links</a>
htmlproofer 3.8.0 | Error:  HTML-Proofer found 1 failure!
```

**Comment by bvhme** [comment]
Whoop ✅all checks have passed,

This is ready to merge :)

**Pull request merged**
